#!/bin/bash

# Usage:
# udef A=42 B=4.2 -> #define A (42)\n#define B (4.2)

awk '
BEGIN {
    if (ARGV[1] == "-h" || ARGV[1] == "--help") usg()
    for (i = 1; i < ARGC; i++) {
	a = ARGV[i]
	p = index(a, "=")
	if (p == 0) file(a)
	else {
	    k = substr(a,     1, p - 1)
	    v = substr(a, p + 1)
	    keyval(k, v)
	}
    }
}
function file(f,  cmd) {
    cmd = sprintf("cat -- \"%s\"", f)
    system(cmd)
}
function keyval(key, val) { printf "#define %s (%s)\n", key, val }
function err(s) { printf "%s\n", s | "cat >&2"; usg() }
function usg(s) { print  "usage: udef [KEY=VAL].." | "cat >&2"; exit }
' "$@"

# TEST: udef.t0
# udef A=42 B=4.2 > def.out.h

# TEST: udef.t1
# udef A=42 B=\"preved\" > def.out.h

# TEST: udef.t2
# udef A=42 B=\"preved\" test_data/conf.h   > def.out.h
#
  
